---
id: mean-build
name: Build the Mean Application
type: task

targets:
  - mean-node

triggers:
  webhooks:
    - path: rebuild/mean/app

vars:
  mean_dir: /opt/meanjs
  mean_git: https://github.com/meanjs/mean.git

steps:
  # Clone or update the mean app
  - run: devops git update
    options:
      repo: "{{ mean_git }}"
      dest: "{{ mean_dir }}"

  # Run the required build operations
  - run: devops scripts/mean-build.sh

  # Register the new nodejs application to start at boot
  - run: devops nodejs app_add
    options:
      name: mean_app
      root: "{{ mean_dir }}"
      script: server.js
      node_env: production
      user: devops

