---
id: mean-build
name: Build the Mean Application
type: task

targets:
  - mean-node

triggers:
  webhooks:
    - path: rebuild/mean/app
  events:
    - node.mean-node.create.success


steps:
  # Clone or update the mean app
  - run: devops git update
    options:
      repo: '{{ git_url }}'
      dest: '/opt/{{ app_name }}'

  # Run the required build operations
  - run: devops scripts/mean-build.sh
    options:
      WORKDIR: '/opt/{{ app_name }}'

  # Register the new nodejs application to start at boot
  - run: devops nodejs app_add
    options:
      name: mean_app
      root: '/opt/{{ app_name }}'
      script: server.js
      node_env: production
      user: devops

